import type { Metadata } from "next";
import localFont from "next/font/local";
import { LocaleProvider } from "@/providers/locale-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { ReactElement } from "react";
import { ThemeSelector } from "@/components/theme-selector";
import { LocaleSelector } from "@/components/locale-selector";
// @ts-expect-error-next-line
import "../globals.css";

const jost = localFont({
  src: "../../public/fonts/jost/Jost-VariableFont_wght.woff2",
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: {
  params: Promise<{ locale: string }>;
  children: ReactElement;
}) {
  const { locale } = await params;
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${jost.variable} antialiased`}>
        <LocaleProvider locale={locale}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <div className="fixed bottom-16 right-16 z-50 flex gap-4">
              <LocaleSelector />
              <ThemeSelector />
            </div>
          </ThemeProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
